Wiki_Vere_Whittome/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
	path("new_page", views.new_page, name="new_page"),
	path("edit/<str:edit_name>", views.edit, name="edit"),
	path("random" , views.random_entry, name="random"),
	path("<str:entry_name>", views.entry, name="entry"),


]

Wiki_Vere_Whittome/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

Wiki_Vere_Whittome/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

Wiki_Vere_Whittome/wiki/encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import util
import random
import markdown2


class New_Page_Form(forms.Form):
	title = forms.CharField(label="title")
	text = forms.CharField(widget=forms.Textarea, label="text")


	
def index(request):
	if request.method == 'POST':
		query_string = request.POST['query_string']
		print(query_string)
		entries = util.list_entries()
		result = [entry for entry in entries if query_string in entry]
		
		entry = util.get_entry(query_string)
		if util.get_entry(query_string):
			return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"entry_name":query_string}))
		elif result:
			return render(request, "encyclopedia/index.html", {
		    "entries": result,
			"title": "Search Results",
			"heading": "Search Results"
			})
	
	return render(request, "encyclopedia/index.html", {
		"entries": util.list_entries(),
		"title": "Encyclopedia",
		"heading": "All Pages"
	})


def new_page(request):
	if request.method == 'POST':
		form = New_Page_Form(request.POST)
		if form.is_valid():
			title = form.cleaned_data["title"]
			if util.get_entry(title):
				return HttpResponse("Entry '{}' already exists".format(title))
			else:

				text = form.cleaned_data["text"]
				path_folder = "./entries"
				md_file = "{}/{}.md".format(path_folder,title)
				with open(md_file, 'w') as f:
					f.write(text)
				return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"entry_name":title}))

	return render(request, "encyclopedia/new_page.html", {
        "form": New_Page_Form(),
		"title": "New Page"
		})

	
def entry(request, entry_name):
	entry = markdown2.markdown(util.get_entry(entry_name))
	if entry:
		return render(request, "encyclopedia/entry.html", {
        "entry": entry,
		"title": entry_name
		})
	else :
		return HttpResponse("Error: File not found")

		

def edit(request, edit_name):
	if request.method == 'POST':
		text = request.POST['text']
		title = edit_name
		path_folder = "./entries"
		md_file = "{}/{}.md".format(path_folder,title)
		with open(md_file, 'w') as f:
			f.write(text)
		return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"entry_name":title}))

	return render(request, "encyclopedia/edit.html", {
		"entry_title": edit_name,
		"title": "Edit",
		"entry": util.get_entry(edit_name),
		})

def random_entry(request):
	entries = util.list_entries()
	random_entry = random.choice(entries)
	return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"entry_name":random_entry}))
	

Wiki_Vere_Whittome/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}



{% block body %}
  	<h1>{{ entry_title }} </h1>

	<form action="{% url 'encyclopedia:edit' edit_name=entry_title %}" method='post'>	
		{% csrf_token %}
		{{ form }}

		<textarea name="text"> {{ entry }} </textarea>

		<input type='submit'></input>
	</form>




{% endblock %}

Wiki_Vere_Whittome/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}



{% block body %}
  	{% autoescape off%}
	{{ entry }}
	{%endautoescape%}
	<br>
	<a href="{% url 'encyclopedia:edit' edit_name=title %}">Edit Page</a>


{% endblock %}

Wiki_Vere_Whittome/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}



{% block body %}
    <h1> {{ heading }} </h1>

    <ul>
        {% for entry in entries %}
            <li> <a href="{% url 'encyclopedia:entry' entry_name=entry %}"> {{ entry }} </a> </li>
        {% endfor %}
    </ul>

{% endblock %}

Wiki_Vere_Whittome/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{{title}}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="post">
					{% csrf_token %}
                    <input class="search" type="text" name="query_string" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}"> Random Page </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

Wiki_Vere_Whittome/wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}



{% block body %}
 <form action="{% url 'encyclopedia:new_page' %}" method='post'>
	{% csrf_token %}
 	{{ form }}
	<input type='submit'></submit>
 </form>


{% endblock %}